# Generated by Django 5.0.1 on 2024-02-28 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIBA_Cloud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_groupe', to='NIBA_Cloud_app.section')),
            ],
        ),
    ]
